/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GallerySplatRouteImport } from './routes/gallery.$'
import { Route as ApiSlotsRouteImport } from './routes/api/slots'
import { Route as ApiGalleryRouteImport } from './routes/api/gallery'
import { Route as ApiBookingsRouteImport } from './routes/api/bookings'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api/telegram/webhook'
import { Route as ApiCronRemindersRouteImport } from './routes/api/cron/reminders'
import { Route as ApiAdminSlotsRouteImport } from './routes/api/admin/slots'
import { Route as ApiAdminMeRouteImport } from './routes/api/admin/me'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminGalleryRouteImport } from './routes/api/admin/gallery'
import { Route as ApiAdminBookingsRouteImport } from './routes/api/admin/bookings'
import { Route as ApiPaymentsPaymentIdStatusRouteImport } from './routes/api/payments/$paymentId/status'
import { Route as ApiPaymentsPaymentIdMockPayRouteImport } from './routes/api/payments/$paymentId/mock-pay'
import { Route as ApiPaymentsPaymentIdCheckoutRouteImport } from './routes/api/payments/$paymentId/checkout'
import { Route as ApiAdminGalleryIdRouteImport } from './routes/api/admin/gallery/$id'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GallerySplatRoute = GallerySplatRouteImport.update({
  id: '/gallery/$',
  path: '/gallery/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSlotsRoute = ApiSlotsRouteImport.update({
  id: '/api/slots',
  path: '/api/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGalleryRoute = ApiGalleryRouteImport.update({
  id: '/api/gallery',
  path: '/api/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsRoute = ApiBookingsRouteImport.update({
  id: '/api/bookings',
  path: '/api/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram/webhook',
  path: '/api/telegram/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRemindersRoute = ApiCronRemindersRouteImport.update({
  id: '/api/cron/reminders',
  path: '/api/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSlotsRoute = ApiAdminSlotsRouteImport.update({
  id: '/api/admin/slots',
  path: '/api/admin/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMeRoute = ApiAdminMeRouteImport.update({
  id: '/api/admin/me',
  path: '/api/admin/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGalleryRoute = ApiAdminGalleryRouteImport.update({
  id: '/api/admin/gallery',
  path: '/api/admin/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBookingsRoute = ApiAdminBookingsRouteImport.update({
  id: '/api/admin/bookings',
  path: '/api/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsPaymentIdStatusRoute =
  ApiPaymentsPaymentIdStatusRouteImport.update({
    id: '/api/payments/$paymentId/status',
    path: '/api/payments/$paymentId/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentsPaymentIdMockPayRoute =
  ApiPaymentsPaymentIdMockPayRouteImport.update({
    id: '/api/payments/$paymentId/mock-pay',
    path: '/api/payments/$paymentId/mock-pay',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentsPaymentIdCheckoutRoute =
  ApiPaymentsPaymentIdCheckoutRouteImport.update({
    id: '/api/payments/$paymentId/checkout',
    path: '/api/payments/$paymentId/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminGalleryIdRoute = ApiAdminGalleryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminGalleryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/gallery': typeof ApiGalleryRoute
  '/api/slots': typeof ApiSlotsRoute
  '/gallery/$': typeof GallerySplatRoute
  '/api/admin/bookings': typeof ApiAdminBookingsRoute
  '/api/admin/gallery': typeof ApiAdminGalleryRouteWithChildren
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/slots': typeof ApiAdminSlotsRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/admin/gallery/$id': typeof ApiAdminGalleryIdRoute
  '/api/payments/$paymentId/checkout': typeof ApiPaymentsPaymentIdCheckoutRoute
  '/api/payments/$paymentId/mock-pay': typeof ApiPaymentsPaymentIdMockPayRoute
  '/api/payments/$paymentId/status': typeof ApiPaymentsPaymentIdStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/gallery': typeof ApiGalleryRoute
  '/api/slots': typeof ApiSlotsRoute
  '/gallery/$': typeof GallerySplatRoute
  '/api/admin/bookings': typeof ApiAdminBookingsRoute
  '/api/admin/gallery': typeof ApiAdminGalleryRouteWithChildren
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/slots': typeof ApiAdminSlotsRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/admin/gallery/$id': typeof ApiAdminGalleryIdRoute
  '/api/payments/$paymentId/checkout': typeof ApiPaymentsPaymentIdCheckoutRoute
  '/api/payments/$paymentId/mock-pay': typeof ApiPaymentsPaymentIdMockPayRoute
  '/api/payments/$paymentId/status': typeof ApiPaymentsPaymentIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/gallery': typeof ApiGalleryRoute
  '/api/slots': typeof ApiSlotsRoute
  '/gallery/$': typeof GallerySplatRoute
  '/api/admin/bookings': typeof ApiAdminBookingsRoute
  '/api/admin/gallery': typeof ApiAdminGalleryRouteWithChildren
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/slots': typeof ApiAdminSlotsRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/admin/gallery/$id': typeof ApiAdminGalleryIdRoute
  '/api/payments/$paymentId/checkout': typeof ApiPaymentsPaymentIdCheckoutRoute
  '/api/payments/$paymentId/mock-pay': typeof ApiPaymentsPaymentIdMockPayRoute
  '/api/payments/$paymentId/status': typeof ApiPaymentsPaymentIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api/bookings'
    | '/api/gallery'
    | '/api/slots'
    | '/gallery/$'
    | '/api/admin/bookings'
    | '/api/admin/gallery'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/slots'
    | '/api/cron/reminders'
    | '/api/telegram/webhook'
    | '/api/admin/gallery/$id'
    | '/api/payments/$paymentId/checkout'
    | '/api/payments/$paymentId/mock-pay'
    | '/api/payments/$paymentId/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api/bookings'
    | '/api/gallery'
    | '/api/slots'
    | '/gallery/$'
    | '/api/admin/bookings'
    | '/api/admin/gallery'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/slots'
    | '/api/cron/reminders'
    | '/api/telegram/webhook'
    | '/api/admin/gallery/$id'
    | '/api/payments/$paymentId/checkout'
    | '/api/payments/$paymentId/mock-pay'
    | '/api/payments/$paymentId/status'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/bookings'
    | '/api/gallery'
    | '/api/slots'
    | '/gallery/$'
    | '/api/admin/bookings'
    | '/api/admin/gallery'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/slots'
    | '/api/cron/reminders'
    | '/api/telegram/webhook'
    | '/api/admin/gallery/$id'
    | '/api/payments/$paymentId/checkout'
    | '/api/payments/$paymentId/mock-pay'
    | '/api/payments/$paymentId/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiBookingsRoute: typeof ApiBookingsRoute
  ApiGalleryRoute: typeof ApiGalleryRoute
  ApiSlotsRoute: typeof ApiSlotsRoute
  GallerySplatRoute: typeof GallerySplatRoute
  ApiAdminBookingsRoute: typeof ApiAdminBookingsRoute
  ApiAdminGalleryRoute: typeof ApiAdminGalleryRouteWithChildren
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminMeRoute: typeof ApiAdminMeRoute
  ApiAdminSlotsRoute: typeof ApiAdminSlotsRoute
  ApiCronRemindersRoute: typeof ApiCronRemindersRoute
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
  ApiPaymentsPaymentIdCheckoutRoute: typeof ApiPaymentsPaymentIdCheckoutRoute
  ApiPaymentsPaymentIdMockPayRoute: typeof ApiPaymentsPaymentIdMockPayRoute
  ApiPaymentsPaymentIdStatusRoute: typeof ApiPaymentsPaymentIdStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$': {
      id: '/gallery/$'
      path: '/gallery/$'
      fullPath: '/gallery/$'
      preLoaderRoute: typeof GallerySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/slots': {
      id: '/api/slots'
      path: '/api/slots'
      fullPath: '/api/slots'
      preLoaderRoute: typeof ApiSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gallery': {
      id: '/api/gallery'
      path: '/api/gallery'
      fullPath: '/api/gallery'
      preLoaderRoute: typeof ApiGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings': {
      id: '/api/bookings'
      path: '/api/bookings'
      fullPath: '/api/bookings'
      preLoaderRoute: typeof ApiBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/webhook': {
      id: '/api/telegram/webhook'
      path: '/api/telegram/webhook'
      fullPath: '/api/telegram/webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/reminders': {
      id: '/api/cron/reminders'
      path: '/api/cron/reminders'
      fullPath: '/api/cron/reminders'
      preLoaderRoute: typeof ApiCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/slots': {
      id: '/api/admin/slots'
      path: '/api/admin/slots'
      fullPath: '/api/admin/slots'
      preLoaderRoute: typeof ApiAdminSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/me': {
      id: '/api/admin/me'
      path: '/api/admin/me'
      fullPath: '/api/admin/me'
      preLoaderRoute: typeof ApiAdminMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/gallery': {
      id: '/api/admin/gallery'
      path: '/api/admin/gallery'
      fullPath: '/api/admin/gallery'
      preLoaderRoute: typeof ApiAdminGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bookings': {
      id: '/api/admin/bookings'
      path: '/api/admin/bookings'
      fullPath: '/api/admin/bookings'
      preLoaderRoute: typeof ApiAdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/$paymentId/status': {
      id: '/api/payments/$paymentId/status'
      path: '/api/payments/$paymentId/status'
      fullPath: '/api/payments/$paymentId/status'
      preLoaderRoute: typeof ApiPaymentsPaymentIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/$paymentId/mock-pay': {
      id: '/api/payments/$paymentId/mock-pay'
      path: '/api/payments/$paymentId/mock-pay'
      fullPath: '/api/payments/$paymentId/mock-pay'
      preLoaderRoute: typeof ApiPaymentsPaymentIdMockPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/$paymentId/checkout': {
      id: '/api/payments/$paymentId/checkout'
      path: '/api/payments/$paymentId/checkout'
      fullPath: '/api/payments/$paymentId/checkout'
      preLoaderRoute: typeof ApiPaymentsPaymentIdCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/gallery/$id': {
      id: '/api/admin/gallery/$id'
      path: '/$id'
      fullPath: '/api/admin/gallery/$id'
      preLoaderRoute: typeof ApiAdminGalleryIdRouteImport
      parentRoute: typeof ApiAdminGalleryRoute
    }
  }
}

interface ApiAdminGalleryRouteChildren {
  ApiAdminGalleryIdRoute: typeof ApiAdminGalleryIdRoute
}

const ApiAdminGalleryRouteChildren: ApiAdminGalleryRouteChildren = {
  ApiAdminGalleryIdRoute: ApiAdminGalleryIdRoute,
}

const ApiAdminGalleryRouteWithChildren = ApiAdminGalleryRoute._addFileChildren(
  ApiAdminGalleryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiBookingsRoute: ApiBookingsRoute,
  ApiGalleryRoute: ApiGalleryRoute,
  ApiSlotsRoute: ApiSlotsRoute,
  GallerySplatRoute: GallerySplatRoute,
  ApiAdminBookingsRoute: ApiAdminBookingsRoute,
  ApiAdminGalleryRoute: ApiAdminGalleryRouteWithChildren,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminMeRoute: ApiAdminMeRoute,
  ApiAdminSlotsRoute: ApiAdminSlotsRoute,
  ApiCronRemindersRoute: ApiCronRemindersRoute,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
  ApiPaymentsPaymentIdCheckoutRoute: ApiPaymentsPaymentIdCheckoutRoute,
  ApiPaymentsPaymentIdMockPayRoute: ApiPaymentsPaymentIdMockPayRoute,
  ApiPaymentsPaymentIdStatusRoute: ApiPaymentsPaymentIdStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
