/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PaymentSuccessRouteImport } from './routes/payment/success'
import { Route as PaymentCancelRouteImport } from './routes/payment/cancel'
import { Route as PaymentPaymentIdRouteImport } from './routes/payment/$paymentId'
import { Route as GallerySplatRouteImport } from './routes/gallery.$'
import { Route as ApiSlotsRouteImport } from './routes/api/slots'
import { Route as ApiGalleryRouteImport } from './routes/api/gallery'
import { Route as ApiBookingsRouteImport } from './routes/api/bookings'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api/telegram/webhook'
import { Route as ApiCronRemindersRouteImport } from './routes/api/cron/reminders'
import { Route as ApiAdminTestEmailRouteImport } from './routes/api/admin/test-email'
import { Route as ApiAdminSlotsRouteImport } from './routes/api/admin/slots'
import { Route as ApiAdminResendPaymentEmailRouteImport } from './routes/api/admin/resend-payment-email'
import { Route as ApiAdminMeRouteImport } from './routes/api/admin/me'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminGalleryRouteImport } from './routes/api/admin/gallery'
import { Route as ApiAdminBookingsRouteImport } from './routes/api/admin/bookings'
import { Route as ApiPaymentsAntilopayCallbackRouteImport } from './routes/api/payments/antilopay/callback'
import { Route as ApiPaymentsPaymentIdStatusRouteImport } from './routes/api/payments/$paymentId/status'
import { Route as ApiPaymentsPaymentIdMockPayRouteImport } from './routes/api/payments/$paymentId/mock-pay'
import { Route as ApiPaymentsPaymentIdCheckoutRouteImport } from './routes/api/payments/$paymentId/checkout'
import { Route as ApiAdminSlotsRemoveRouteImport } from './routes/api/admin/slots/remove'
import { Route as ApiAdminSlotsIdRouteImport } from './routes/api/admin/slots/$id'
import { Route as ApiAdminGalleryIdRouteImport } from './routes/api/admin/gallery/$id'
import { Route as ApiAdminBookingsRemoveRouteImport } from './routes/api/admin/bookings/remove'
import { Route as ApiAdminBookingsIdRouteImport } from './routes/api/admin/bookings/$id'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCancelRoute = PaymentCancelRouteImport.update({
  id: '/payment/cancel',
  path: '/payment/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentPaymentIdRoute = PaymentPaymentIdRouteImport.update({
  id: '/payment/$paymentId',
  path: '/payment/$paymentId',
  getParentRoute: () => rootRouteImport,
} as any)
const GallerySplatRoute = GallerySplatRouteImport.update({
  id: '/gallery/$',
  path: '/gallery/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSlotsRoute = ApiSlotsRouteImport.update({
  id: '/api/slots',
  path: '/api/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGalleryRoute = ApiGalleryRouteImport.update({
  id: '/api/gallery',
  path: '/api/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingsRoute = ApiBookingsRouteImport.update({
  id: '/api/bookings',
  path: '/api/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram/webhook',
  path: '/api/telegram/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRemindersRoute = ApiCronRemindersRouteImport.update({
  id: '/api/cron/reminders',
  path: '/api/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTestEmailRoute = ApiAdminTestEmailRouteImport.update({
  id: '/api/admin/test-email',
  path: '/api/admin/test-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSlotsRoute = ApiAdminSlotsRouteImport.update({
  id: '/api/admin/slots',
  path: '/api/admin/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminResendPaymentEmailRoute =
  ApiAdminResendPaymentEmailRouteImport.update({
    id: '/api/admin/resend-payment-email',
    path: '/api/admin/resend-payment-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminMeRoute = ApiAdminMeRouteImport.update({
  id: '/api/admin/me',
  path: '/api/admin/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGalleryRoute = ApiAdminGalleryRouteImport.update({
  id: '/api/admin/gallery',
  path: '/api/admin/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBookingsRoute = ApiAdminBookingsRouteImport.update({
  id: '/api/admin/bookings',
  path: '/api/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsAntilopayCallbackRoute =
  ApiPaymentsAntilopayCallbackRouteImport.update({
    id: '/api/payments/antilopay/callback',
    path: '/api/payments/antilopay/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentsPaymentIdStatusRoute =
  ApiPaymentsPaymentIdStatusRouteImport.update({
    id: '/api/payments/$paymentId/status',
    path: '/api/payments/$paymentId/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentsPaymentIdMockPayRoute =
  ApiPaymentsPaymentIdMockPayRouteImport.update({
    id: '/api/payments/$paymentId/mock-pay',
    path: '/api/payments/$paymentId/mock-pay',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentsPaymentIdCheckoutRoute =
  ApiPaymentsPaymentIdCheckoutRouteImport.update({
    id: '/api/payments/$paymentId/checkout',
    path: '/api/payments/$paymentId/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminSlotsRemoveRoute = ApiAdminSlotsRemoveRouteImport.update({
  id: '/remove',
  path: '/remove',
  getParentRoute: () => ApiAdminSlotsRoute,
} as any)
const ApiAdminSlotsIdRoute = ApiAdminSlotsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminSlotsRoute,
} as any)
const ApiAdminGalleryIdRoute = ApiAdminGalleryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminGalleryRoute,
} as any)
const ApiAdminBookingsRemoveRoute = ApiAdminBookingsRemoveRouteImport.update({
  id: '/remove',
  path: '/remove',
  getParentRoute: () => ApiAdminBookingsRoute,
} as any)
const ApiAdminBookingsIdRoute = ApiAdminBookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminBookingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/gallery': typeof ApiGalleryRoute
  '/api/slots': typeof ApiSlotsRoute
  '/gallery/$': typeof GallerySplatRoute
  '/payment/$paymentId': typeof PaymentPaymentIdRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/api/admin/bookings': typeof ApiAdminBookingsRouteWithChildren
  '/api/admin/gallery': typeof ApiAdminGalleryRouteWithChildren
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/resend-payment-email': typeof ApiAdminResendPaymentEmailRoute
  '/api/admin/slots': typeof ApiAdminSlotsRouteWithChildren
  '/api/admin/test-email': typeof ApiAdminTestEmailRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/admin/bookings/$id': typeof ApiAdminBookingsIdRoute
  '/api/admin/bookings/remove': typeof ApiAdminBookingsRemoveRoute
  '/api/admin/gallery/$id': typeof ApiAdminGalleryIdRoute
  '/api/admin/slots/$id': typeof ApiAdminSlotsIdRoute
  '/api/admin/slots/remove': typeof ApiAdminSlotsRemoveRoute
  '/api/payments/$paymentId/checkout': typeof ApiPaymentsPaymentIdCheckoutRoute
  '/api/payments/$paymentId/mock-pay': typeof ApiPaymentsPaymentIdMockPayRoute
  '/api/payments/$paymentId/status': typeof ApiPaymentsPaymentIdStatusRoute
  '/api/payments/antilopay/callback': typeof ApiPaymentsAntilopayCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/gallery': typeof ApiGalleryRoute
  '/api/slots': typeof ApiSlotsRoute
  '/gallery/$': typeof GallerySplatRoute
  '/payment/$paymentId': typeof PaymentPaymentIdRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/api/admin/bookings': typeof ApiAdminBookingsRouteWithChildren
  '/api/admin/gallery': typeof ApiAdminGalleryRouteWithChildren
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/resend-payment-email': typeof ApiAdminResendPaymentEmailRoute
  '/api/admin/slots': typeof ApiAdminSlotsRouteWithChildren
  '/api/admin/test-email': typeof ApiAdminTestEmailRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/admin/bookings/$id': typeof ApiAdminBookingsIdRoute
  '/api/admin/bookings/remove': typeof ApiAdminBookingsRemoveRoute
  '/api/admin/gallery/$id': typeof ApiAdminGalleryIdRoute
  '/api/admin/slots/$id': typeof ApiAdminSlotsIdRoute
  '/api/admin/slots/remove': typeof ApiAdminSlotsRemoveRoute
  '/api/payments/$paymentId/checkout': typeof ApiPaymentsPaymentIdCheckoutRoute
  '/api/payments/$paymentId/mock-pay': typeof ApiPaymentsPaymentIdMockPayRoute
  '/api/payments/$paymentId/status': typeof ApiPaymentsPaymentIdStatusRoute
  '/api/payments/antilopay/callback': typeof ApiPaymentsAntilopayCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/bookings': typeof ApiBookingsRoute
  '/api/gallery': typeof ApiGalleryRoute
  '/api/slots': typeof ApiSlotsRoute
  '/gallery/$': typeof GallerySplatRoute
  '/payment/$paymentId': typeof PaymentPaymentIdRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/api/admin/bookings': typeof ApiAdminBookingsRouteWithChildren
  '/api/admin/gallery': typeof ApiAdminGalleryRouteWithChildren
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/resend-payment-email': typeof ApiAdminResendPaymentEmailRoute
  '/api/admin/slots': typeof ApiAdminSlotsRouteWithChildren
  '/api/admin/test-email': typeof ApiAdminTestEmailRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/admin/bookings/$id': typeof ApiAdminBookingsIdRoute
  '/api/admin/bookings/remove': typeof ApiAdminBookingsRemoveRoute
  '/api/admin/gallery/$id': typeof ApiAdminGalleryIdRoute
  '/api/admin/slots/$id': typeof ApiAdminSlotsIdRoute
  '/api/admin/slots/remove': typeof ApiAdminSlotsRemoveRoute
  '/api/payments/$paymentId/checkout': typeof ApiPaymentsPaymentIdCheckoutRoute
  '/api/payments/$paymentId/mock-pay': typeof ApiPaymentsPaymentIdMockPayRoute
  '/api/payments/$paymentId/status': typeof ApiPaymentsPaymentIdStatusRoute
  '/api/payments/antilopay/callback': typeof ApiPaymentsAntilopayCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api/bookings'
    | '/api/gallery'
    | '/api/slots'
    | '/gallery/$'
    | '/payment/$paymentId'
    | '/payment/cancel'
    | '/payment/success'
    | '/api/admin/bookings'
    | '/api/admin/gallery'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/resend-payment-email'
    | '/api/admin/slots'
    | '/api/admin/test-email'
    | '/api/cron/reminders'
    | '/api/telegram/webhook'
    | '/api/admin/bookings/$id'
    | '/api/admin/bookings/remove'
    | '/api/admin/gallery/$id'
    | '/api/admin/slots/$id'
    | '/api/admin/slots/remove'
    | '/api/payments/$paymentId/checkout'
    | '/api/payments/$paymentId/mock-pay'
    | '/api/payments/$paymentId/status'
    | '/api/payments/antilopay/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api/bookings'
    | '/api/gallery'
    | '/api/slots'
    | '/gallery/$'
    | '/payment/$paymentId'
    | '/payment/cancel'
    | '/payment/success'
    | '/api/admin/bookings'
    | '/api/admin/gallery'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/resend-payment-email'
    | '/api/admin/slots'
    | '/api/admin/test-email'
    | '/api/cron/reminders'
    | '/api/telegram/webhook'
    | '/api/admin/bookings/$id'
    | '/api/admin/bookings/remove'
    | '/api/admin/gallery/$id'
    | '/api/admin/slots/$id'
    | '/api/admin/slots/remove'
    | '/api/payments/$paymentId/checkout'
    | '/api/payments/$paymentId/mock-pay'
    | '/api/payments/$paymentId/status'
    | '/api/payments/antilopay/callback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/bookings'
    | '/api/gallery'
    | '/api/slots'
    | '/gallery/$'
    | '/payment/$paymentId'
    | '/payment/cancel'
    | '/payment/success'
    | '/api/admin/bookings'
    | '/api/admin/gallery'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/admin/resend-payment-email'
    | '/api/admin/slots'
    | '/api/admin/test-email'
    | '/api/cron/reminders'
    | '/api/telegram/webhook'
    | '/api/admin/bookings/$id'
    | '/api/admin/bookings/remove'
    | '/api/admin/gallery/$id'
    | '/api/admin/slots/$id'
    | '/api/admin/slots/remove'
    | '/api/payments/$paymentId/checkout'
    | '/api/payments/$paymentId/mock-pay'
    | '/api/payments/$paymentId/status'
    | '/api/payments/antilopay/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiBookingsRoute: typeof ApiBookingsRoute
  ApiGalleryRoute: typeof ApiGalleryRoute
  ApiSlotsRoute: typeof ApiSlotsRoute
  GallerySplatRoute: typeof GallerySplatRoute
  PaymentPaymentIdRoute: typeof PaymentPaymentIdRoute
  PaymentCancelRoute: typeof PaymentCancelRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ApiAdminBookingsRoute: typeof ApiAdminBookingsRouteWithChildren
  ApiAdminGalleryRoute: typeof ApiAdminGalleryRouteWithChildren
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminMeRoute: typeof ApiAdminMeRoute
  ApiAdminResendPaymentEmailRoute: typeof ApiAdminResendPaymentEmailRoute
  ApiAdminSlotsRoute: typeof ApiAdminSlotsRouteWithChildren
  ApiAdminTestEmailRoute: typeof ApiAdminTestEmailRoute
  ApiCronRemindersRoute: typeof ApiCronRemindersRoute
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
  ApiPaymentsPaymentIdCheckoutRoute: typeof ApiPaymentsPaymentIdCheckoutRoute
  ApiPaymentsPaymentIdMockPayRoute: typeof ApiPaymentsPaymentIdMockPayRoute
  ApiPaymentsPaymentIdStatusRoute: typeof ApiPaymentsPaymentIdStatusRoute
  ApiPaymentsAntilopayCallbackRoute: typeof ApiPaymentsAntilopayCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/cancel': {
      id: '/payment/cancel'
      path: '/payment/cancel'
      fullPath: '/payment/cancel'
      preLoaderRoute: typeof PaymentCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/$paymentId': {
      id: '/payment/$paymentId'
      path: '/payment/$paymentId'
      fullPath: '/payment/$paymentId'
      preLoaderRoute: typeof PaymentPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$': {
      id: '/gallery/$'
      path: '/gallery/$'
      fullPath: '/gallery/$'
      preLoaderRoute: typeof GallerySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/slots': {
      id: '/api/slots'
      path: '/api/slots'
      fullPath: '/api/slots'
      preLoaderRoute: typeof ApiSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gallery': {
      id: '/api/gallery'
      path: '/api/gallery'
      fullPath: '/api/gallery'
      preLoaderRoute: typeof ApiGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bookings': {
      id: '/api/bookings'
      path: '/api/bookings'
      fullPath: '/api/bookings'
      preLoaderRoute: typeof ApiBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/webhook': {
      id: '/api/telegram/webhook'
      path: '/api/telegram/webhook'
      fullPath: '/api/telegram/webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/reminders': {
      id: '/api/cron/reminders'
      path: '/api/cron/reminders'
      fullPath: '/api/cron/reminders'
      preLoaderRoute: typeof ApiCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/test-email': {
      id: '/api/admin/test-email'
      path: '/api/admin/test-email'
      fullPath: '/api/admin/test-email'
      preLoaderRoute: typeof ApiAdminTestEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/slots': {
      id: '/api/admin/slots'
      path: '/api/admin/slots'
      fullPath: '/api/admin/slots'
      preLoaderRoute: typeof ApiAdminSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/resend-payment-email': {
      id: '/api/admin/resend-payment-email'
      path: '/api/admin/resend-payment-email'
      fullPath: '/api/admin/resend-payment-email'
      preLoaderRoute: typeof ApiAdminResendPaymentEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/me': {
      id: '/api/admin/me'
      path: '/api/admin/me'
      fullPath: '/api/admin/me'
      preLoaderRoute: typeof ApiAdminMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/gallery': {
      id: '/api/admin/gallery'
      path: '/api/admin/gallery'
      fullPath: '/api/admin/gallery'
      preLoaderRoute: typeof ApiAdminGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bookings': {
      id: '/api/admin/bookings'
      path: '/api/admin/bookings'
      fullPath: '/api/admin/bookings'
      preLoaderRoute: typeof ApiAdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/antilopay/callback': {
      id: '/api/payments/antilopay/callback'
      path: '/api/payments/antilopay/callback'
      fullPath: '/api/payments/antilopay/callback'
      preLoaderRoute: typeof ApiPaymentsAntilopayCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/$paymentId/status': {
      id: '/api/payments/$paymentId/status'
      path: '/api/payments/$paymentId/status'
      fullPath: '/api/payments/$paymentId/status'
      preLoaderRoute: typeof ApiPaymentsPaymentIdStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/$paymentId/mock-pay': {
      id: '/api/payments/$paymentId/mock-pay'
      path: '/api/payments/$paymentId/mock-pay'
      fullPath: '/api/payments/$paymentId/mock-pay'
      preLoaderRoute: typeof ApiPaymentsPaymentIdMockPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/$paymentId/checkout': {
      id: '/api/payments/$paymentId/checkout'
      path: '/api/payments/$paymentId/checkout'
      fullPath: '/api/payments/$paymentId/checkout'
      preLoaderRoute: typeof ApiPaymentsPaymentIdCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/slots/remove': {
      id: '/api/admin/slots/remove'
      path: '/remove'
      fullPath: '/api/admin/slots/remove'
      preLoaderRoute: typeof ApiAdminSlotsRemoveRouteImport
      parentRoute: typeof ApiAdminSlotsRoute
    }
    '/api/admin/slots/$id': {
      id: '/api/admin/slots/$id'
      path: '/$id'
      fullPath: '/api/admin/slots/$id'
      preLoaderRoute: typeof ApiAdminSlotsIdRouteImport
      parentRoute: typeof ApiAdminSlotsRoute
    }
    '/api/admin/gallery/$id': {
      id: '/api/admin/gallery/$id'
      path: '/$id'
      fullPath: '/api/admin/gallery/$id'
      preLoaderRoute: typeof ApiAdminGalleryIdRouteImport
      parentRoute: typeof ApiAdminGalleryRoute
    }
    '/api/admin/bookings/remove': {
      id: '/api/admin/bookings/remove'
      path: '/remove'
      fullPath: '/api/admin/bookings/remove'
      preLoaderRoute: typeof ApiAdminBookingsRemoveRouteImport
      parentRoute: typeof ApiAdminBookingsRoute
    }
    '/api/admin/bookings/$id': {
      id: '/api/admin/bookings/$id'
      path: '/$id'
      fullPath: '/api/admin/bookings/$id'
      preLoaderRoute: typeof ApiAdminBookingsIdRouteImport
      parentRoute: typeof ApiAdminBookingsRoute
    }
  }
}

interface ApiAdminBookingsRouteChildren {
  ApiAdminBookingsIdRoute: typeof ApiAdminBookingsIdRoute
  ApiAdminBookingsRemoveRoute: typeof ApiAdminBookingsRemoveRoute
}

const ApiAdminBookingsRouteChildren: ApiAdminBookingsRouteChildren = {
  ApiAdminBookingsIdRoute: ApiAdminBookingsIdRoute,
  ApiAdminBookingsRemoveRoute: ApiAdminBookingsRemoveRoute,
}

const ApiAdminBookingsRouteWithChildren =
  ApiAdminBookingsRoute._addFileChildren(ApiAdminBookingsRouteChildren)

interface ApiAdminGalleryRouteChildren {
  ApiAdminGalleryIdRoute: typeof ApiAdminGalleryIdRoute
}

const ApiAdminGalleryRouteChildren: ApiAdminGalleryRouteChildren = {
  ApiAdminGalleryIdRoute: ApiAdminGalleryIdRoute,
}

const ApiAdminGalleryRouteWithChildren = ApiAdminGalleryRoute._addFileChildren(
  ApiAdminGalleryRouteChildren,
)

interface ApiAdminSlotsRouteChildren {
  ApiAdminSlotsIdRoute: typeof ApiAdminSlotsIdRoute
  ApiAdminSlotsRemoveRoute: typeof ApiAdminSlotsRemoveRoute
}

const ApiAdminSlotsRouteChildren: ApiAdminSlotsRouteChildren = {
  ApiAdminSlotsIdRoute: ApiAdminSlotsIdRoute,
  ApiAdminSlotsRemoveRoute: ApiAdminSlotsRemoveRoute,
}

const ApiAdminSlotsRouteWithChildren = ApiAdminSlotsRoute._addFileChildren(
  ApiAdminSlotsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiBookingsRoute: ApiBookingsRoute,
  ApiGalleryRoute: ApiGalleryRoute,
  ApiSlotsRoute: ApiSlotsRoute,
  GallerySplatRoute: GallerySplatRoute,
  PaymentPaymentIdRoute: PaymentPaymentIdRoute,
  PaymentCancelRoute: PaymentCancelRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ApiAdminBookingsRoute: ApiAdminBookingsRouteWithChildren,
  ApiAdminGalleryRoute: ApiAdminGalleryRouteWithChildren,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminMeRoute: ApiAdminMeRoute,
  ApiAdminResendPaymentEmailRoute: ApiAdminResendPaymentEmailRoute,
  ApiAdminSlotsRoute: ApiAdminSlotsRouteWithChildren,
  ApiAdminTestEmailRoute: ApiAdminTestEmailRoute,
  ApiCronRemindersRoute: ApiCronRemindersRoute,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
  ApiPaymentsPaymentIdCheckoutRoute: ApiPaymentsPaymentIdCheckoutRoute,
  ApiPaymentsPaymentIdMockPayRoute: ApiPaymentsPaymentIdMockPayRoute,
  ApiPaymentsPaymentIdStatusRoute: ApiPaymentsPaymentIdStatusRoute,
  ApiPaymentsAntilopayCallbackRoute: ApiPaymentsAntilopayCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
